### ISSUE TITLE
Powerwall version 21.20.5 - No Data

### ISSUE THREAD

**Issue by natrlhy** [liveaverage/docker-powerwall-dashboard#20]
I got another update to 21.20.5 and am not sure but may be some authentication issues again? I'm not seeing data again...

**Comment by natrlhy** [comment]
Not sure how often the cookie gets updated, but since 9pm last night, I see data again:

![image](https://user-images.githubusercontent.com/19696424/125815996-ccec2feb-002c-4966-85ff-9546485a65aa.png)

**Comment by liveaverage** [comment]
I experienced similar issues... this is related to the TEG and not the dashboard app. The [cookie is updated every 4h](https://github.com/liveaverage/docker-powerwall-dashboard/blob/master/powerwallcookie.sh.template#L58) and is entirely configurable if you're building your own image.

 I actually had to login to by my Backup Gateway (manually) and click "Start System" ... post-firmware update (which happened around the same time as yours), I lost connectivity via Tesla app and started receiving 502 errors when polling the local API. You can open a case with Tesla WRT connectivity reliability. I recently did the same since I noticed inconsistent network connectivity via Wifi + LTE post update to 21.20.2... apparently code QC at Telsa is going a bit downhill.

**Comment by natrlhy** [comment]
Yeah I've seen that as well WRT to needing to start the system after logging into the TEG web UI. I ended up hardwiring my TEG since I was seeing data gaps throughout the day and since then it's been solid, until of course, their latest FW update :)

**Comment by liveaverage** [comment]
I also had it hardwired but still experienced connectivity issues... I
opted to leave that switchport open for another UBNT AC-Mesh since
connectivity is spotty across all methods. I requested escalation of the
issue since I could pinpoint *when* I began experiencing problems relative
to firmware updates. Since the 21.20.2 release I've had to physically reset
the TEG (3) times due to complete loss of connectivity...

**Comment by natrlhy** [comment]
Wow, I have yet to hit the glowing reset button... I saw it when getting access to the LAN port on the Gateway.
