### ISSUE TITLE
Powerwall version 20.49.0 requires authentication

### ISSUE THREAD

**Issue by DavidW-GIT** [liveaverage/docker-powerwall-dashboard#7]
Latest version of Powerwall firmware/update 20.49.0 requires authentication for all API calls.  Any way to fix?

**Comment by liveaverage** [comment]
Thanks for bringing this up. Let me work through a solution and post documentation!

**Comment by Nakatomi2010** [comment]
Looks like the original posted a solution about a month ago or so.  Not sure if you can just pull that down and recycle it?

Unless it is still not working.

**Comment by liveaverage** [comment]
Solid comment timing -- was actually working on this over the weekend. While reusing some parts was possible, the hard part was automating refresh of the cookie & telegraf config. First draft was just checked in but note that it might not be fully-functional yet. 

https://github.com/liveaverage/docker-powerwall-dashboard/commit/2fe84bb528107e4f6a947b44058fe21db8d29581

Due to Dockerhub limits, also moving automated builds to Quay: 

https://quay.io/repository/liveaverage/powerwall-dashboard/build/98746ad6-5cb2-449b-a4ff-b0ef34d80ba3

**Comment by Nakatomi2010** [comment]
I'm about migrate away from this running on a Pi to running on an Ubuntu VM alongside a Docker instance of TeslaMate.

How can I import the data from the non docker PowerDash instance?

**Comment by liveaverage** [comment]
@Obiji1 the latest build should be working fine: https://quay.io/repository/liveaverage/powerwall-dashboard/build/82f6cb0a-8299-4c18-8859-c9d472b1ead1

This will run a cron script hourly that creates/validates/recreates a cookie for auth, replaces auth detail in the telegraf `powerwall.conf` file, then SIGHUP to the telegraf PID for configuration reload without any downtime.

@Nakatomi2010 assuming same data structure from a previous deployment you should be able to preseed the `influxdb/data` with your prexisting data. Reference the proper hostpath dir (at the toplevel for influxdb) after preseeding. The same applies if you've customized any dashboards... just reference the proper hostpath when establishing the volume:

```
        -v ${LOCAL_INFLUXDB_PATH}:/var/lib/influxdb:z \
        -v ${LOCAL_GRAFANA_PATH}:/var/lib/grafana:z \
```

**Comment by liveaverage** [comment]
Closing this out since it's resolved with the latest image version... I've had mine running without issue for 1+ week
